nature_testing_set_expected_words = {
    '0': ["freedom"],
    '1': ["homogenic"],
    '2': ["bison vodka"],
    '3': ["tesco race for life cancer research uk"],
    '4': ["tesco value washing up liquid"],
    '5': ["fire alarm call point"],
    '6': ["you are here 4b.528 4b.526 4b.524 4b.522"],
    '7': ["access to know"],
    '8': ["iiyama"],
    '9': ["use only dri-wipe markers on these boards"],
    '10': ["computing service help desk 2n"],
    '11': ["c.c.t.v. in operation"],
    '12': ["please no paper"],
    '13': ["no entry when red light is flashing"],
    '14': ["overseas relations office"],
    '15': ["night exit on floor 4"],
    '16': ["sorry toilet out of order"],
    '17': ["robert just to let u know being a student does not give u licence to live like a tramp! do!"],
    '18': ["warning! low flying and departing aircraft blast can cause physical injury"],
    '19': ["beware alligator teeth"],
    '20': ["proceed with caution. height when raisesd 115mm"],
    '21': ["beardwell construction limited construction refurbishment maintenance"],
    '22': ["boundary road"],
    '23': ["clock museum tymperleys"],
    '24': ["essex county council libraries"],
    '25': ["welcome to marks & spencer collect by car"],
    '26': ["whsmith"],
    '27': ["red lion yard shops high street"],
    '28': ["summer whatever the weather"],
    '29': ["summer's here!"],
    '30': ["rough guide website directory angus"],
    '31': ["professional java soap henry bequet"],
    '32': ["java tm language guide by guy steele"],
    '33': ["j2se"],
    '34': ["colchester post office"],
    '35': ["beer garden"],
    '36': ["please lock the gate"],
    '37': ["hotel"],
    '38': ["dental surgery"],
    '39': ["holsten pure lager"],
    '40': ["fca foster care associates"],
    '41': ["middleborough"],
    '42': ["royal london"],
    '43': ["nhs"],
    '44': ["connells"],
    '45': ["hsbc the world's local bank"],
    '46': ["house seatrade communications ltd registered office"],
    '47': ["warning trespassing or causing nuisance on a school site can lead to a criminal conviction under section 547 of the education act 1996 essexx county council learning services"],
    '48': ["gt. yarmouth ipswich harwich clacton A133"],
    '49': ["london chelmsford a 12"],
    '50': ["good home made food cask conditioned ales garden"],
    '51': ["new traffic signals ahead"],
    '52': ["town centre a 134"],
    '53': ["essex"],
    '54': ["proper food pronto"],
    '55': ["park & ride sats. only"],
    '56': ["station car park"],
    '57': ["information tickets trains"],
    '58': ["cycleway closed ahead"],
    '59': ["colchester"],
    '60': ["investments pensions mortgages"],
    '61': ["drivers stop here and report to warehouse office."],
    '62': ["need a brolly? just ask!"],
    '63': ["asda car park"],
    '64': ["royal mail"],
    '65': ["2002 manchester the xvii commonwealth games"],
    '66': ["f foster's"],
    '67': ["guinness draught 17 59"],
    '68': ["corona extra"],
    '69': ["imported beer from mexico"],
    '70': ["customer freephone private hire service"],
    '71': ["pedestrians"],
    '72': ["15'"],
    '73': ["town centre leisure world rollerworld clacton a 133 ipswich gt. yarmouth harwich london chelmsford"],
    '74': ["leisure ccentre ipswich road greenstead"],
    '75': ["the albert"],
    '76': ["osborne garages"],
    '77': ["isuzu order your"],
    '78': ["central tyre m.o.t."],
    '79': ["school"],
    '80': ["good year"],
    '81': ["bed breakfast"],
    '82': ["saloon"],
    '83': ["hair"],
    '84': ["fax"],
    '85': ["free delivery"],
    '86': ["coral"],
    '87': ["refill"],
    '88': ["riverside walk"],
    '89': ["discover the dark side"],
    '90': ["airtours holidays hotel"],
    '91': ["lloyds bank"],
    '92': ["the photo specialists"],
    '93': ["british red cross shop"],
    '94': ["stationery box"],
    '95': ["inspiron 8000"],
    '96': ["canon compact power adapter ca-ps100"],
    '97': ["farnborough airshow 28 july 2002 daily flying programme"],
    '98': ["bae systems"],
    '99': ["mexico a publication of the mexican embassy to the united kingdom president fox visits european cities"],
    '100': ['"the heart of a fool is in his mouth, but the mouth of a wise man is in his heart." (benjamin franklin)'],
    '101': ["4b.522 2n gradiate office marisa bostock jenny dixon"],
    '102': ["iiyama"],
    '103': ["avery"],
    '104': ["guidex folders"],
    '105': ["pro xtra x multimedia projector"],
    '106': ["roland digital group"],
    '107': ["invent"],
    '108': ["no mobile phones"],
    '109': ["microsoft"],
    '110': ["dioxide extinguisher"],
    '111': [":hansol"],
    '112': ["num lock caps lock scroll lock"],
    '113': ["raf careers"],
    '114': ["matsui cd 77"],
    '115': ["pocket flash"],
    '116': ["waterstone's the last word in books"],
    '117': ["electrolux"],
    '118': ["zanussi"],
    '119': ["panasonic ne-1027"],
    '120': ["fresh semi skimmed"],
    '121': ["please do not disturb ...im recovering!!"],
    '122': ["henry"],
    '123': ["sainsbury's economy lounge life orange juice"],
    '124': ["no aunauthorised entry into this area! permit to work system in operation estates management section"],
    '125': ["nightline"],
    '126': ["accomodation office nightline"],
    '127': ["footpath to colchester and greenstead"],
    '128': ["campus"],
    '129': ["five fours 2a arthur st colchester 544444 licensed private hire vehicle"],
    '130': ["arena colchester at the heart of the town!"],
    '131': ["lounge"],
    '132': ["gentlemen"],
    '133': ["ladies"],
    '134': ["st. helena room"],
    '135': ["constantine room"],
    '136': ["push"],
    '137': ["pull"],
    '138': ["break glass in case of fire"],
    '139': ["toyota"],
    '140': ["arena leisure services limited registered office"],
    '141': ["carling"],
    '142': ["no admittance authorised personnel only"],
    '143': ["colchester"],
    '144': ["way out"],
    '145': ["exit"],
    '146': ["tan"],
    '147': ["telephone"],
    '148': ["health"],
    '149': ["beaver84 tel: 01268 530888"],
    '150': ["portakabin"],
    '151': ["rayleigh"],
    '152': ["health centre greenwood house"],
    '153': ["barclays"],
    '154': ["campus shop"],
    '155': ["colgate fluoride toothpaste"],
    '156': ["laboratoires garnier"],
    '157': ["pantene pro-v"],
    '158': ["coolmint listerine"],
    '159': ["professional xml 2nd edition"],
    '160': ["professional java web services"],
    '161': ["espanol-ingles ingles-espanol"],
    '162': ["wallace monument"],
    '163': ["you are here"],
    '164': ["gates 30 & 88 emergency exit"],
    '165': ["the wallace sword"],
    '166': ["scottsh nation gellery modern"],
    '167': ["hall of heroes"],
    '168': ["dollar glen and castle campbell"],
    '169': ["ancient monument castle campbell"],
    '170': ["reserved for club secretary"],
    '171': ["west burnside"],
    '172': ["the dollar arms"],
    '173': ["castle campbell"],
    '174': ["no footway for 450 yds"],
    '175': ["stirling castle argyll's lodgings"],
}