nature_training_set_expected_words = {
    '0': ["22 washington"],
    '1': ["postgrad study"],
    '84': ["emergency stop"],
    '159': ["pepsi"],
    '169': ["the rab butler building no beyond point"],
    '179': ["professional recorable compact disc universal compatibility 700 24x powered european top memorex"],
    '187': ["tesco race for life cancer research uk"],
    '196': ["tesco value washing up liquid"],
    '215': ["essex summer school in data analysis"],
    '2': ["you are here"],
    '13': ["department of government courses for staff"],
    '21': ["iiyama pocket flash reader"],
    '32': ["technology for life"],
    '44': ["graphic java mastering the jfc 2 3rd edition"],
    '52': ["wrigley's doublemint chewing gum"],
    '74': ["kenco"],
    '85': ["espresso espressochoc hot milk chocomilk 52 53 54 55 20p"],
    '96': ["fire hose reel"],
    '105': ["exclusively for wheelchair users"],
    '121': ["fire break glass press here"],
    '127': ["department of computer science 1"],
    '137': ["yamaha"],
    '142': ["D"],
    '143': ["B"],
    '152': ["sports center wivennoe ark conference centre car parks"],
    '160': ["blanco 3 2 1 0"],
    '161': ["a l i e n"],
    '162': ["human traffic"],
    '163': ["boo"],
    '164': ["xml"],
    '165': ["coldfusion express"],
    '166': ["september"],
    '167': ["belfast city hospital"],
    '168': ["mp65"],
    '170': ["equal opportunities monitoring"],
    '171': ["reminder"],
    '172': ["application form"],
    '173': ["black pepper"],
    '174': ["post office"],
    '175': ["tiredness kills a short break could save your life"],
    '176': ["jubilee line"],
    '177': ["7 day travelcards from a machine"],
    '178': ["closing down sale"],
    '180': ["peacocks"],
    '181': ["spirit doubles gin whisky vodka special house whisky"],
    '182': ["jacks famous supplies est 1946"],
    '183': ["please wait here until a chashier is available free travel"],
    '184': ["do you know anyone starting university this year student accounts"],
    '185': ["pay in account balance mini-statement cheque book ordering there are alternative chas machines at the culver street end of"],
    '186': ["break glass for key"],
    '188': ["p p"],
    '189': ["final clearance burton"],
    '190': ["14 june 2002 the uk's no.1 hard house dj is back!"],
    '191': ["30'-6"],
    '192': ["healthy colchester 2000"],
    '193': ["all our videos are loaned for one week"],
    '194': ["videos here"],
    '195': ["lion walk"],
    '197': ["no cycling"],
    '198': ["one hour the eyecare clinic contact lens centre"],
    '199': ["famous for our fish & chips"],
    '200': ["fire exit keep clear"],
    '201': ["restaurant"],
    '202': ["99"],
    '203': ["5 sprinkler valve chamber"],
    '204': ["the linen factory"],
    '205': ["ice cream"],
    '206': ["dry cleaning limited special offer"],
    '207': ["play here"],
    '208': ["20p a ride"],
    '209': ["peacocks"],
    '210': ["slush puppie as cool as it gets"],
    '211': ["cheques"],
    '212': ["the adult community college"],
    '213': ["11"],
    '214': ["fire up your senses"],
    '216': ["save 4"],
    '217': ["except for access and buses"],
    '218': ["priory galleries at the ship"],
    '219': ["tanfords"],
    '220': ["no smoking maximum penalty"],
    '221': ["colchester insurance centre"],
    '222': ["east hill"],
    '223': ["chips cut over 4,000 prices chopped"],
    '3': ["mill antiques"],
    '4': ["hamblion transport storage & distribution colchester 794447"],
    '5': ["university of essex gas station no 6"],
    '6': ["dry riser"],
    '7': ["department of psychology second year"],
    '8': ["floor 3"],
    '9': ["national express"],
    '10': ["postpak post office"],
    '11': ["the copy centre"],
    '12': ["colour laser copies"],
    '14': ["tetley U"],
    '15': ["to find out just"],
    '16': ["hellmann parcel systems"],
    '17': ["shop to let"],
    '18': ["oxfam bookshop"],
    '19': ["no smoking beyond this point"],
    '20': ["e g intelligent inhabited environments group"],
    '22': ["samsung pocket flash upgrade your digital life!"],
    '23': ["george orwell animal farm"],
    '24': ["self-adhesive address labels 250 on a roll"],
    '25': ["natwest"],
    '26': ["greek cookery & wines"],
    '27': ["isabel allende house spirits intensely moving. both entertaining and deeply serious"],
    '28': ["digital multimedia nigel chapman and jenny chapman wiley"],
    '29': ["software design for real-time syustem j. e. cooling"],
    '30': ["nokia cable dlr-3p 6210 data"],
    '31': ["professional issues in software engineering frank bott allison coleman jack eaton diane rowland third edition"],
    '33': ["fifth edition"],
    '34': ["nformation systems series systems analysis stems design mason & leslie willcocks business strategy"],
    '35': ["second edition of hardware alan clements"],
    '36': ["ian sommerville"],
    '37': ["create sony"],
    '38': ["handle with care please return to: future publishing ltd, somerton, ta11 6tb, united kingdom."],
    '39': ["stuart russel peter norvig a modern approach intelligence"],
    '40': ["essence of computing the essence of artificial intelligence"],
    '41': ["marlboro lights"],
    '42': ["autumn/winter 2001"],
    '43': ["philips fisio 820e"],
    '45': ["orange experience the revolution with orange to order your v70e on orange, please call 150 and press"],
    '46': ["of summer live music events orange"],
    '47': ["building web services with java making sense of xml, soap, wsdl, and uddi"],
    '48': ["nick hornby high fidelity"],
    '49': ["mark z. danielewski house of leaves"],
    '50': ["john steinbeck the grapes of wrath"],
    '51': ["heart of darkness joseph conrad"],
    '53': ["truman capote breakfast tiffany's"],
    '54': ["nad ir"],
    '55': ["4.5 5 4"],
    '56': ["garden path at giverny claude monet"],
    '57': ["join the rugby club"],
    '58': ["gallery 1 please enter"],
    '59': ["size queen"],
    '60': ["ah! colchester arts handbook 2002"],
    '61': ["litter colchester borough"],
    '62': ["2"],
    '63': ["estate agents saxons"],
    '64': ["closeout! final reductions"],
    '65': ["natwest"],
    '66': ["past times"],
    '67': ["essex county council colchester library"],
    '68': ["library open essex county council libraries"],
    '69': ["forum trinity street studios"],
    '70': ["private car park lion walk church"],
    '71': ["while you wait shoe repairs available"],
    '72': ["zone ends"],
    '73': ["queen street formerly southgate street"],
    '75': ["route"],
    '76': ["we cash cheques on the spot"],
    '77': ["bus"],
    '78': ["tourist information castle"],
    '79': ["hills residential &"],
    '80': ["maynard dixon images of the native american"],
    '81': ["rogers"],
    '82': ["first aid for this dept. is available from"],
    '83': ["carter 10"],
    '86': ["harwich court house 11"],
    '87': ["gas"],
    '88': ["fire door keep locked"],
    '89': ["east court house"],
    '90': ["tesco"],
    '91': ["exit service vehicles"],
    '92': ["you are here student residence"],
    '93': ["anti nazi leauge black & white unite"],
    '94': ["celmac"],
    '95': ["plant room no unauthorised entry into this area! permit to work system in operation estates management section"],
    '97': ["coach stop national express"],
    '98': ["first"],
    '99': ["used tickets"],
    '100': ["alarm fitted"],
    '101': ["fire extinguisher break glass"],
    '102': ["casual plus"],
    '103': ["new superkings meet the big three. 002101"],
    '104': ["in the interest of health and hygiene please do not feed the pigeons"],
    '106': ["fired earth"],
    '107': ["home entertainment"],
    '108': ["hfc bank"],
    '109': ["star wars episode attack of the clones"],
    '110': ["spider-man"],
    '111': ["natural history museum"],
    '112': ["act one bar .co.uk"],
    '113': ["fun fashion ladies lingerie shop 01206 368166 funfashion@hotmail.com"],
    '114': ["p s 3"],
    '115': ["counselling helpline lifelines family support"],
    '116': ["first eastern national bus times"],
    '117': ["next departure"],
    '118': ["emergency door control"],
    '119': ["know your first ticket!"],
    '120': ["londown ipswich (a12) town centre longridge p"],
    '122': ["buffett way cul-de-sac"],
    '123': ["danger keep out"],
    '124': ["university of essex leading to wivenhoe trail greenstead centre 1"],
    '125': ["university of essex day nursery the houses keynes, rayleigh, tawney and william morris towers wolfson court buses and cycles only congerence car park entrance 4"],
    '126': ["stop"],
    '128': ["the south colonnade e14"],
    '129': ["cabot place"],
    '130': ["meditative rose (1958)"],
    '131': ["canary wharf station"],
    '132': ["exmouth mews"],
    '133': ["simon lucas department of computer science"],
    '134': ["caution site traffic crossing"],
    '135': ["drivers beware! contractor's vehicles"],
    '136': ["rose builders & contractors"],
    '138': ["accommodation office south campus"],
    '139': ["cans only brow flass only"],
    '140': ["beware alligator teeth"],
    '141': ["gas sv 180 T 2,0"],
    '144': ["stanley kubrick's the"],
    '145': ["roland digital group"],
    '146': ["571"],
    '147': ["4b.532"],
    '148': ["food"],
    '149': ["udx mayfair mini"],
    '150': ["road atlas great britain and ireland aa"],
    '151': ["exit"],
    '153': ["emergency service vehicles only"],
    '154': ["challenge"],
    '155': ["6-5"],
    '156': ["homer simpson my kind guy"],
    '157': ["pizza speciale dr.oetker"],
    '158': ["the one-line go"],
}